<Project>
  <ItemGroup Condition="'$(MSBuildProjectName)' == 'CatClipComposer' Or '$(MSBuildProjectName)' == 'CatClipComposer.Cli'">
    <None Include="$(MSBuildThisFileDirectory)thirdparty\ffmpeg\**\*"
          Link="thirdparty\ffmpeg\%(RecursiveDir)%(Filename)%(Extension)"
          CopyToOutputDirectory="PreserveNewest"
          CopyToPublishDirectory="PreserveNewest" />
  </ItemGroup>
  <ItemGroup Condition="'$(MSBuildProjectName)' == 'CatClipComposer'">
    <None Include="$(MSBuildThisFileDirectory)fonts\**\*"
          Link="fonts\%(RecursiveDir)%(Filename)%(Extension)"
          CopyToOutputDirectory="PreserveNewest"
          CopyToPublishDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
