<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CatClipComposer.Core\CatClipComposer.Core.csproj" />
    <ProjectReference Include="..\CatClipComposer.Infrastructure\CatClipComposer.Infrastructure.csproj" />
    <ProjectReference Include="..\CatClipComposer.Plugins.BuiltIn\CatClipComposer.Plugins.BuiltIn.csproj"
                      ReferenceOutputAssembly="false" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\mr-cat-bee-splash.png" />
  </ItemGroup>

</Project>
